### ISSUE TITLE
Builds longer than an hour don't display duration in header correctly

### ISSUE THREAD

**Issue by Arkadionos** [tophat/jenkins-timeline-plugin#89]
**Describe the bug**
If a build takes longer than an hour to build, only the number of minutes and seconds are displayed in the duration shown, but not the number of hours. This causes some misleading duration strings in the dashboard header

**To Reproduce**
Run a build that takes over an hour to complete, view dashboard header.

**Expected behavior**
Full duration should be listed in the dashboard header.

**Screenshots**
![duration](https://user-images.githubusercontent.com/12653464/66233523-9d113680-e6b9-11e9-9e99-18c5829d3047.PNG)

**Comment by mcataford** [comment]
Hi @Arkadionos! Thank you for reporting this issue! Is this something you would like to take on?

**Comment by mcataford** [comment]
Looks like this should have been addressed by #97 ! Going to close this issue since it looks like it aligns and ties that loose end. :rocket: Don't hesitate to reopen it if the issue persists!

The new containing the fix will be released on the Jenkins repository within a day or so, until then you can try it out by building from source!
